/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.Loader.setConfig({enabled: false});
Ext.Loader.setPath('Ext.ux', 'app/ux');
Ext.application({
    models: [
        'Contact'
    ],
    views: [
        'Viewport',
        'ContactList',
        'ContactForm'
    ],
    requires: [
        'Phonebook.overrides.grid.column.Action'
    ],
    name: 'Phonebook',

    launch: function() {
        Ext.setGlyphFontFamily('FontAwesome');
        Ext.create('Phonebook.view.Viewport');
    }

});
