/*
 * File: app/view/ContactList.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Phonebook.view.ContactList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.contactlist',

    requires: [
        'Phonebook.view.ContactListViewModel',
        'Phonebook.view.ContactListViewController',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Text',
        'Ext.form.trigger.Trigger',
        'Ext.toolbar.Paging',
        'Ext.ux.form.SearchField'
    ],

    controller: 'contactlist',
    viewModel: {
        type: 'contactlist'
    },
    reference: 'contactlist',
    forceFit: true,

    bind: {
        store: '{contacts}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'id',
            text: 'iD'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'firstname',
            text: 'Имя'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'lastname',
            text: 'Фамилия'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'phone',
            text: 'Телефон'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'date_added',
            text: 'Дата добавления'
        },
        {
            xtype: 'actioncolumn',
            width: 50,
            hidden: USER['group'] != 'ADMIN',
            items: [{
                    glyph: 0xf044,
                    tooltip: 'Редактировать',
                    hidden: USER['group'] != 'ADMIN',
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                        var controller = view.lookupController();
                        controller.editRow(record);
                    }
                },
                {
                    glyph: 0xf014,
                    tooltip: 'Удалить',
                    hidden: USER['group'] != 'ADMIN',
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        var controller = view.lookupController();
                        controller.removeRow(record);
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    glyph: 0xf007,
                    text: USER['name'],
                    menu: [{
                        text: 'Выйти',
                        listeners: {
                            click: 'logout'
                        }
                    }]
                },
                {
                    xtype: 'tbseparator',
                    hidden: USER['group'] != 'ADMIN'
                },
                {
                    glyph: 0xf196,
                    xtype: 'button',
                    hidden: USER['group'] != 'ADMIN',
                    text: 'Добавить',
                    listeners: {
                        click: 'onAddButtonClick'
                    }
                },
                {
                    glyph: 0xf014,
                    xtype: 'button',
                    text: 'Удалить',
                    hidden: USER['group'] != 'ADMIN',
                    bind: {
                        disabled: '{!contactlist.selection}'
                    },
                    listeners: {
                        click: 'onRemoveButtonClick'
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                /*{
                    xtype: 'tbfill'
                },*/
                {
                    xtype: 'searchfield',
                    emptyText: 'Введите имя, фамилию или телефон...',
                    width: 350,
                    bind: {
                        store: '{contacts}'
                    }
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            bind: {
                store: '{contacts}'
            }
        }
    ],
    listeners: {
        removeRow: 'removeRow',
        rowdblclick: 'onRowDblClick'
    }

});