/*
 * File: app/view/ContactForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Phonebook.view.ContactForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.contactform',
    border: false,
    requires: [
        'Phonebook.view.ContactFormViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Text'
    ],
    controller: 'contactform',
    viewModel: {
        type: 'contactform'
    },
    width: 400,
    bodyPadding: 10,
    title: 'Контакт',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Сохранить',
                    handler: 'onSaveClick'
                },
                {
                    xtype: 'button',
                    text: 'Отмена',
                    handler: 'onCancelClick'
                }
            ]
        }
    ],
    items: [
        {
            border: false,
            reference: 'fieldform',
            xtype: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Имя',
                    allowBlank: false,
                    emptyText: 'Введите имя контакта...',
                    bind: '{theContact.firstname}'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Фамилия',
                    allowBlank: false,
                    emptyText: 'Введите фамилию контакта...',
                    bind: '{theContact.lastname}'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    allowBlank: false,
                    fieldLabel: 'Контактный номер',
                    emptyText: '8XXXXXXXXXX',
                    bind: '{theContact.phone}'
                }
            ]
        }
    ]

});