/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Phonebook.view.Viewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.viewport',

    requires: [
        'Phonebook.view.ViewportViewModel',
        'Phonebook.view.ContactList',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'viewport'
    },
    layout: 'border',

    items: [
        {
            region: 'north',
            xtype: 'panel',
            bodyPadding: '8 8 0 8',
            height: 65,
            html: '<img class="logo" src="/images/logo1.png" />'
        },
        {
            region: 'center',
            border: false,
            xtype: 'contactlist'
        }
    ]

});